# Generated by Django 5.1.14 on 2026-09-11 07:05

import bots.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0091_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshareFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('timestamp_ms', models.BigIntegerField()),
                ('dhash', models.CharField(max_length=16)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file', models.FileField(storage=bots.storage.StorageAlias('recordings'), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshare_frames', to='bots.participant')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshare_frames', to='bots.recording')),
            ],
        ),
    ]
